### ISSUE TITLE
关于同义词synoyms.txt  的错误

### ISSUE THREAD

**Issue by yyhjifeng** [sing1ee/elasticsearch-jieba-plugin#18]
环境：es 5.3.0    jieba 5.3.0
按照readme 一步一步到 
========= OK ==========
test analyzer:
GET http://localhost:9200/jieba_index/_analyze?analyzer=my_ana&text=中国的伟大时代来临了，欢迎参观北京大学PKU

========================

================添加同义词 出错 ========

Pay attention to *jieba_synonym, same with jieba_stop, the format of synoyms.txt:
北京大学,北大,pku
清华大学,清华,Tsinghua University

===》 这一步我修改对应的文件synoyms.txt 后，重启 es ，会报错。日志如下 （如果是空内容是不会出错）

[2018-08-10T15:48:55,535][WARN ][o.e.g.Gateway            ] [7ixgH36] recovering index [welink_index/7MYv9V1JSs-DAF8CBEKULA] failed - recovering as closed
java.lang.IllegalArgumentException: failed to build synonyms
        at org.elasticsearch.index.analysis.SynonymTokenFilterFactory.<init>(SynonymTokenFilterFactory.java:97) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.index.analysis.AnalysisRegistry.lambda$buildTokenFilterFactories$1(AnalysisRegistry.java:169) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.index.analysis.AnalysisRegistry$1.get(AnalysisRegistry.java:265) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:342) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.index.analysis.AnalysisRegistry.buildTokenFilterFactories(AnalysisRegistry.java:171) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:155) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.index.IndexService.<init>(IndexService.java:145) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:363) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:427) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.indices.IndicesService.verifyIndexMetadata(IndicesService.java:460) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.gateway.Gateway.performStateRecovery(Gateway.java:135) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.gateway.GatewayService$1.doRun(GatewayService.java:229) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:613) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.3.0.jar:5.3.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281) ~[?:1.8.0_171]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339) ~[?:?]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:?]
        at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_171]
        at java.io.BufferedReader.read1(BufferedReader.java:210) ~[?:1.8.0_171]
        at java.io.BufferedReader.read(BufferedReader.java:286) ~[?:1.8.0_171]
        at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:1.8.0_171]
        at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[?:1.8.0_171]
        at java.io.LineNumberReader.readLine(LineNumberReader.java:201) ~[?:1.8.0_171]
        at org.apache.lucene.analysis.synonym.SolrSynonymParser.addInternal(SolrSynonymParser.java:82) ~[lucene-analyzers-common-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:44:09]
        at org.apache.lucene.analysis.synonym.SolrSynonymParser.parse(SolrSynonymParser.java:70) ~[lucene-analyzers-common-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:44:09]
        at org.elasticsearch.index.analysis.SynonymTokenFilterFactory.<init>(SynonymTokenFilterFactory.java:92) ~[elasticsearch-5.3.0.jar:5.3.0]
        ... 16 more

====================================

synoyms.txt 内容是如下格式？？？

北京大学,北大,pku
清华大学,清华,Tsinghua University

========================

Pay attention to *jieba_synonym, same with jieba_stop, the format of synoyms.txt:
北京大学,北大,pku
清华大学,清华,Tsinghua University

**Comment by yyhjifeng** [comment]
问题经过折腾已经解决，  synoyms.txt  文件要以 UTF-8 无BOM格式编码

**Comment by sing1ee** [comment]
@yyhjifeng 👍

**Comment by haowg** [comment]
@yyhjifeng 怎么解决的，为什么我无bom格式也不行，把北京大学四个字删掉才可以

**Comment by haowg** [comment]
@poying https://github.com/sing1ee/elasticsearch-jieba-plugin/commit/2d73484115a5cc3fdf3e9bd2f2082bd37ff472fe 应该是这一次提交导致的bug
