### ISSUE TITLE
加载插件无法启动问题

### ISSUE THREAD

**Issue by nany1999** [sing1ee/elasticsearch-jieba-plugin#72]
elasticsearch
Exception in thread "main" java.nio.file.NotDirectoryException: /usr/local/elasticsearch/7.11.1/plugins/elasticsearch-jieba-plugin-7.4.2.jar
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:407)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:471)
	at java.base/java.nio.file.Files.list(Files.java:3694)
	at org.elasticsearch.tools.launchers.BootstrapJvmOptions.getPluginInfo(BootstrapJvmOptions.java:49)
	at org.elasticsearch.tools.launchers.BootstrapJvmOptions.bootstrapJvmOptions(BootstrapJvmOptions.java:34)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:137)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)

**Comment by sing1ee** [comment]
目录结构不对
```shell

/usr/local/elasticsearch/7.11.1/plugins/elasticsearch-jieba-plugin-7.4.2.jar
```
应该是

```shell
/usr/local/elasticsearch/7.11.1/plugins/jieba/elasticsearch-jieba-plugin-7.4.2.jar
```
