### ISSUE TITLE
elasticsearch8.4.0无法安装

### ISSUE THREAD

**Issue by AnitaSherry** [sing1ee/elasticsearch-jieba-plugin#95]
### git clone https://github.com/sing1ee/elasticsearch-jieba-plugin.git --recursive
无法克隆 'git@github.com:sing1ee/jieba-analysis.git' 到子模组路径 'jieba-analysis' **无效**
最后手动下载了
### ./gradlew clean pz
错误: 找不到或无法加载主类 org.gradle.wrapper.GradleWrapperMain
根据其他人的issue，手动改了gradle/wrapper，**无效**
### 新增分支:
获取了8.4.1分支，修改文件，build.gradle、src/main/resources/plugin-descriptor.properties、切换不同的gradle版本
放入plugins，回到主目录运行./bin/elasticsearch **无效**
总结，浪费一早上时间

**Comment by sing1ee** [comment]
Sorry for the convenience of use.

最后无效是有错误提示么？启动的时候有一步load plugins，如果有问题，es无法启动。

**Comment by AnitaSherry** [comment]
[2023-03-02T11:03:54,289][INFO ][o.e.p.PluginsService     ] [localhost.localdomain] loaded plugin [analysis-ik]
[2023-03-02T11:03:55,754][WARN ][stderr                   ] [localhost.localdomain] 三月 02, 2023 11:03:55 上午 org.apache.lucene.store.MMapDirectory lookupProvider
[2023-03-02T11:03:55,754][WARN ][stderr                   ] [localhost.localdomain] 警告: You are running with Java 19. To make full use of MMapDirectory, please pass '--enable-preview' to the Java command line.
[2023-03-02T11:03:55,760][INFO ][o.e.e.NodeEnvironment    ] [localhost.localdomain] using [1] data paths, mounts [[/home (/dev/mapper/centos-home)]], net usable_space [212.4gb], net total_space [410gb], types [xfs]
[2023-03-02T11:03:55,760][INFO ][o.e.e.NodeEnvironment    ] [localhost.localdomain] heap size [15.6gb], compressed ordinary object pointers [true]
[2023-03-02T11:03:55,794][INFO ][o.e.n.Node               ] [localhost.localdomain] node name [localhost.localdomain], node ID [In7L8AwvQgG8Yv7irop60w], cluster name [elasticsearch], roles [data_cold, data, remote_cluster_client, master, data_warm, data_content, transform, data_hot, ml, data_frozen, ingest]
[2023-03-02T11:03:57,522][INFO ][o.e.x.s.Security         ] [localhost.localdomain] Security is disabled
[2023-03-02T11:03:57,558][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [localhost.localdomain] [controller/2530] [Main.cc@123] controller (64 bit): Version 8.6.0 (Build 85eb78d83cdd94) Copyright (c) 2022 Elasticsearch BV
[2023-03-02T11:03:57,826][INFO ][o.e.t.n.NettyAllocator   ] [localhost.localdomain] creating NettyAllocator with the following configs: [name=elasticsearch_configured, chunk_size=1mb, suggested_max_allocation_size=1mb, factors={es.unsafe.use_netty_default_chunk_and_page_size=false, g1gc_enabled=true, g1gc_region_size=8mb}]
[2023-03-02T11:03:57,840][INFO ][o.e.i.r.RecoverySettings ] [localhost.localdomain] using rate limit [40mb] with [default=40mb, read=0b, write=0b, max=0b]
[2023-03-02T11:03:57,862][INFO ][o.e.d.DiscoveryModule    ] [localhost.localdomain] using discovery type [multi-node] and seed hosts providers [settings]
[2023-03-02T11:03:58,485][INFO ][o.e.n.Node               ] [localhost.localdomain] initialized
[2023-03-02T11:03:58,485][INFO ][o.e.n.Node               ] [localhost.localdomain] starting ...
[2023-03-02T11:03:58,494][INFO ][o.e.x.s.c.f.PersistentCache] [localhost.localdomain] persistent cache index loaded
[2023-03-02T11:03:58,495][INFO ][o.e.x.d.l.DeprecationIndexingComponent] [localhost.localdomain] deprecation component started
[2023-03-02T11:03:58,543][INFO ][o.e.t.TransportService   ] [localhost.localdomain] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
[2023-03-02T11:03:58,768][WARN ][o.e.b.BootstrapChecks    ] [localhost.localdomain] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2023-03-02T11:03:58,769][WARN ][o.e.c.c.ClusterBootstrapService] [localhost.localdomain] this node is locked into cluster UUID [wm6wrMdHTiKEOIhN1ey0oQ] but [cluster.initial_master_nodes] is set to [localhost.localdomain]; remove this setting to avoid possible data loss caused by subsequent cluster bootstrap attempts
[2023-03-02T11:03:58,822][INFO ][o.e.c.s.MasterService    ] [localhost.localdomain] elected-as-master ([1] nodes joined)[_FINISH_ELECTION_, {localhost.localdomain}{In7L8AwvQgG8Yv7irop60w}{RyVIUdI8TfyhOfZVJagGuw}{localhost.localdomain}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw} completing election], term: 20, version: 465, delta: master node changed {previous [], current [{localhost.localdomain}{In7L8AwvQgG8Yv7irop60w}{RyVIUdI8TfyhOfZVJagGuw}{localhost.localdomain}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw}]}
[2023-03-02T11:03:58,850][INFO ][o.e.c.s.ClusterApplierService] [localhost.localdomain] master node changed {previous [], current [{localhost.localdomain}{In7L8AwvQgG8Yv7irop60w}{RyVIUdI8TfyhOfZVJagGuw}{localhost.localdomain}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw}]}, term: 20, version: 465, reason: Publication{term=20, version=465}
[2023-03-02T11:03:58,867][INFO ][o.e.r.s.FileSettingsService] [localhost.localdomain] starting file settings watcher ...
[2023-03-02T11:03:58,870][INFO ][o.e.r.s.FileSettingsService] [localhost.localdomain] file settings service up and running [tid=78]
[2023-03-02T11:03:58,873][INFO ][o.e.h.AbstractHttpServerTransport] [localhost.localdomain] publish_address {10.10.20.9:9200}, bound_addresses {0.0.0.0:9200}
[2023-03-02T11:03:58,873][INFO ][o.e.n.Node               ] [localhost.localdomain] started {localhost.localdomain}{In7L8AwvQgG8Yv7irop60w}{RyVIUdI8TfyhOfZVJagGuw}{localhost.localdomain}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw}{ml.allocated_processors=12, ml.machine_memory=33502986240, xpack.installed=true, ml.allocated_processors_double=12.0, ml.max_jvm_size=16752050176}
[2023-03-02T11:03:58,972][INFO ][o.e.l.LicenseService     ] [localhost.localdomain] license [5781ccfc-d6f9-4d67-b914-68c14f9b1b70] mode [basic] - valid
[2023-03-02T11:03:58,974][INFO ][o.e.g.GatewayService     ] [localhost.localdomain] recovered [13] indices into cluster_state
[2023-03-02T11:03:59,020][INFO ][o.w.a.d.Dictionary       ] [localhost.localdomain] try load config from /home/heyiheng/drivers/elasticsearch-8.6.0/config/analysis-ik/IKAnalyzer.cfg.xml
[2023-03-02T11:03:59,120][INFO ][o.w.a.d.Dictionary       ] [localhost.localdomain] [Dict Loading] /home/heyiheng/drivers/elasticsearch-8.6.0/config/analysis-ik/my.dic
[2023-03-02T11:03:59,332][INFO ][o.e.h.n.s.HealthNodeTaskExecutor] [localhost.localdomain] Node [{localhost.localdomain}{In7L8AwvQgG8Yv7irop60w}] is selected as the current health node.
[2023-03-02T11:03:59,475][INFO ][o.e.c.r.a.AllocationService] [localhost.localdomain] current.health="YELLOW" message="Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.ds-.logs-deprecation.elasticsearch-default-2023.01.13-000001][0]]])." previous.health="RED" reason="shards started [[.ds-.logs-deprecation.elasticsearch-default-2023.01.13-000001][0]]"
[2023-03-02T11:48:05,532][INFO ][o.e.x.m.p.NativeController] [localhost.localdomain] Native controller process has stopped - no new native processes can be started
[2023-03-02T11:48:05,535][INFO ][o.e.n.Node               ] [localhost.localdomain] stopping ...
[2023-03-02T11:48:05,537][INFO ][o.e.r.s.FileSettingsService] [localhost.localdomain] shutting down watcher thread
[2023-03-02T11:48:05,539][INFO ][o.e.r.s.FileSettingsService] [localhost.localdomain] watcher service stopped
[2023-03-02T11:48:05,541][INFO ][o.e.x.w.WatcherService   ] [localhost.localdomain] stopping watch service, reason [shutdown initiated]
[2023-03-02T11:48:05,541][INFO ][o.e.x.w.WatcherLifeCycleService] [localhost.localdomain] watcher has stopped and shutdown
[2023-03-02T11:48:06,079][INFO ][o.e.n.Node               ] [localhost.localdomain] stopped
[2023-03-02T11:48:06,080][INFO ][o.e.n.Node               ] [localhost.localdomain] closing ...
[2023-03-02T11:48:06,087][INFO ][o.e.n.Node               ] [localhost.localdomain] closed
[2023-03-02T11:48:13,417][INFO ][o.e.n.Node               ] [localhost.localdomain] version[8.6.0], pid[6070], build[tar/f67ef2df40237445caa70e2fef79471cc608d70d/2023-01-04T09:35:21.782467981Z], OS[Linux/3.10.0-1160.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/19.0.1/19.0.1+10-21]
[2023-03-02T11:48:13,420][INFO ][o.e.n.Node               ] [localhost.localdomain] JVM home [/home/heyiheng/drivers/elasticsearch-8.6.0/jdk], using bundled JDK [true]
[2023-03-02T11:48:13,420][INFO ][o.e.n.Node               ] [localhost.localdomain] JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -Djava.security.manager=allow, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-17203655027354955245, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Xms15975m, -Xmx15975m, -XX:MaxDirectMemorySize=8376025088, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=25, -Des.distribution.type=tar, --module-path=/home/heyiheng/drivers/elasticsearch-8.6.0/lib, --add-modules=jdk.net, -Djdk.module.main=org.elasticsearch.server]
[2023-03-02T11:48:13,556][ERROR][o.e.b.Elasticsearch      ] [localhost.localdomain] fatal exception while booting Elasticsearch
java.lang.IllegalStateException: Plugin [elasticsearch-jieba-plugin] is missing a descriptor properties file.
	at org.elasticsearch.plugins.PluginDescriptor.readFromProperties(PluginDescriptor.java:196) ~[elasticsearch-8.6.0.jar:?]
	at org.elasticsearch.plugins.PluginsUtils.readPluginBundle(PluginsUtils.java:162) ~[elasticsearch-8.6.0.jar:?]
	at org.elasticsearch.plugins.PluginsUtils.findBundles(PluginsUtils.java:143) ~[elasticsearch-8.6.0.jar:?]
	at org.elasticsearch.plugins.PluginsUtils.getPluginBundles(PluginsUtils.java:125) ~[elasticsearch-8.6.0.jar:?]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:150) ~[elasticsearch-8.6.0.jar:?]
	at org.elasticsearch.plugins.PluginsService.lambda$getPluginsServiceCtor$14(PluginsService.java:645) ~[elasticsearch-8.6.0.jar:?]
	at org.elasticsearch.node.Node.<init>(Node.java:415) ~[elasticsearch-8.6.0.jar:?]
	at org.elasticsearch.node.Node.<init>(Node.java:322) ~[elasticsearch-8.6.0.jar:?]
	at org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:214) ~[elasticsearch-8.6.0.jar:?]
	at org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:214) ~[elasticsearch-8.6.0.jar:?]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67) ~[elasticsearch-8.6.0.jar:?]

**Comment by sing1ee** [comment]
看起来是打包的问题，缺少了文件
```shell

java.lang.IllegalStateException: Plugin [elasticsearch-jieba-plugin] is missing a descriptor properties file.

```
目录结构应该是这样的：
```shell
~/Downloads/elasticsearch-8.4.1 ⌚ 12:24:32
$ ll plugins/jieba
total 7048
drwxr-xr-x  5 cheng  staff   160B 12  1 13:36 dic
-rw-r--r--  1 cheng  staff   1.3M 12  1 13:36 elasticsearch-jieba-plugin-1.0.0.jar
-rw-r--r--  1 cheng  staff   2.1M 12  1 13:36 jieba-analysis-1.0.1-SNAPSHOT.jar
-rw-r--r--  1 cheng  staff   539B 12  1 13:36 plugin-descriptor.properties
-rw-r--r--  1 cheng  staff   1.4K 12  1 13:36 plugin.xml

```

**Comment by AnitaSherry** [comment]
抱歉，看错了，我用的是8.6.0。但是您给的上述文件我均无找到。

**Comment by sing1ee** [comment]
打包之后，会形成一个zip文件，解压之后，就包含了这个文件。
比如这个是基于7.17.x打包的：
[elasticsearch-jieba-plugin-1.0.0.zip](https://github.com/sing1ee/elasticsearch-jieba-plugin/files/10867641/elasticsearch-jieba-plugin-1.0.0.zip)
