### ISSUE TITLE
在7.15下使用插件，提示error

### ISSUE THREAD

**Issue by cindymuji** [sing1ee/elasticsearch-jieba-plugin#96]
[2023-03-28T14:33:41,991][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-1] uncaught exception in thread [Timer-0]
java.lang.NullPointerException: null
        at com.huaban.analysis.jieba.WordDictionary.init(WordDictionary.java:50) ~[?:?]
        at org.elasticsearch.index.analysis.JiebaDict$1.run(JiebaDict.java:24) ~[?:?]
        at java.util.TimerThread.mainLoop(Timer.java:556) ~[?:?]
        at java.util.TimerThread.run(Timer.java:506) ~[?:?]
uncaught exception in thread [Timer-0]
java.lang.NullPointerException
        at com.huaban.analysis.jieba.WordDictionary.init(WordDictionary.java:50)
        at org.elasticsearch.index.analysis.JiebaDict$1.run(JiebaDict.java:24)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by sing1ee** [comment]
确认下目录结构
```shell
~/Downloads/elasticsearch-7.17.0/plugins ⌚ 14:41:30
$ tree
.
|____jieba
| |____elasticsearch-jieba-plugin-7.17.0.jar
| |____dic
| | |____sougou.dict
| | |____user.dict
| | |____stopwords.txt
| |____plugin.xml
| |____jieba-analysis-1.0.1-SNAPSHOT.jar
| |____plugin-descriptor.properties
```

**Comment by cindymuji** [comment]
目录调整后，原本error没有了，出现了这个，
[2023-03-28T15:49:49,222][ERROR][o.e.i.g.GeoIpDownloader  ] [node-1] exception during geoip databases update
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.waitForConnect(Native Method) ~[?:?]
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
        at java.net.Socket.connect(Socket.java:609) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[?:?]
        at org.elasticsearch.ingest.geoip.HttpClient.lambda$get$0(HttpClient.java:55) ~[ingest-geoip-7.15.2.jar:7.15.2]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.elasticsearch.ingest.geoip.HttpClient.doPrivileged(HttpClient.java:97) ~[ingest-geoip-7.15.2.jar:7.15.2]
        at org.elasticsearch.ingest.geoip.HttpClient.get(HttpClient.java:49) ~[ingest-geoip-7.15.2.jar:7.15.2]
        at org.elasticsearch.ingest.geoip.HttpClient.getBytes(HttpClient.java:40) ~[ingest-geoip-7.15.2.jar:7.15.2]
        at org.elasticsearch.ingest.geoip.GeoIpDownloader.fetchDatabasesOverview(GeoIpDownloader.java:115) ~[ingest-geoip-7.15.2.jar:7.15.2]
        at org.elasticsearch.ingest.geoip.GeoIpDownloader.updateDatabases(GeoIpDownloader.java:103) ~[ingest-geoip-7.15.2.jar:7.15.2]
        at org.elasticsearch.ingest.geoip.GeoIpDownloader.runDownloader(GeoIpDownloader.java:235) [ingest-geoip-7.15.2.jar:7.15.2]
        at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:94) [ingest-geoip-7.15.2.jar:7.15.2]
        at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:43) [ingest-geoip-7.15.2.jar:7.15.2]
        at org.elasticsearch.persistent.NodePersistentTasksExecutor$1.doRun(NodePersistentTasksExecutor.java:40) [elasticsearch-7.15.2.jar:7.15.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737) [elasticsearch-7.15.2.jar:7.15.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.15.2.jar:7.15.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by cindymuji** [comment]
原问题已解决，参考网上的解决方法，在yml里添加：
ingest.geoip.downloader.enabled: false
error的警告都没了。
感谢！
